import React from "react";
import { ShieldCheck, AlertTriangle, UserCheck, Cpu, Database } from "lucide-react";

export default function ProvenanceBadge({ type, confidence, showTooltip = true }) {
  const getBadgeConfig = () => {
    switch (type) {
      case "PATIENT_ENTERED":
        return {
          label: "Patient-Reported",
          color: "bg-emerald-950/70 text-emerald-300 border-emerald-700/60",
          icon: UserCheck,
          tooltip: "Data entered directly by the patient during intake. Provenance: Self-Reported Context."
        };
      case "AI_EXTRACTED_VERIFIED":
        return {
          label: "AI-Verified (Grounded)",
          color: "bg-blue-950/70 text-blue-300 border-blue-700/60",
          icon: ShieldCheck,
          tooltip: `Extracted via OCR/NLP and strictly verified against source document text (${Math.round((confidence || 1) * 100)}% confidence).`
        };
      case "AI_EXTRACTED_NEEDS_REVIEW":
        return {
          label: "Needs Review",
          color: "bg-amber-950/70 text-amber-300 border-amber-700/60",
          icon: AlertTriangle,
          tooltip: "Extracted from document, but reference range absent or ambiguous. Requires clinician review."
        };
      case "HALLUCINATION_BLOCKED":
        return {
          label: "Hallucination Blocked",
          color: "bg-rose-950/80 text-rose-300 border-rose-600",
          icon: AlertTriangle,
          tooltip: "Anti-hallucination guard intercepted fabricated reference range not present in source document."
        };
      case "DERIVED":
      case "SYSTEM":
        return {
          label: "Derived / System",
          color: "bg-purple-950/70 text-purple-300 border-purple-700/60",
          icon: Database,
          tooltip: "Calculated ratio or standard clinical index generated by MedLens engine."
        };
      default:
        return {
          label: type || "Clinical Data",
          color: "bg-slate-800 text-slate-300 border-slate-700",
          icon: Cpu,
          tooltip: "Standard clinical record."
        };
    }
  };

  const config = getBadgeConfig();
  const Icon = config.icon;

  return (
    <span
      className={`inline-flex items-center gap-1.5 px-2.5 py-1 text-xs font-medium rounded-md border ${config.color} transition-all duration-150 cursor-help`}
      title={showTooltip ? config.tooltip : undefined}
    >
      <Icon className="w-3.5 h-3.5 flex-shrink-0" />
      <span>{config.label}</span>
      {confidence && confidence < 1 && confidence > 0.1 && (
        <span className="opacity-75 text-[10px] mono">({Math.round(confidence * 100)}%)</span>
      )}
    </span>
  );
}
